# Generated by Django 2.2.5 on 2021-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('books', 'Books'), ('movies', 'Movies')], default='books', max_length=20),
        ),
    ]
