# Generated by Django 2.2.5 on 2021-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210607_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('books', 'Books'), ('movies', 'Movies')], max_length=20, null=True),
        ),
    ]
