# Generated by Django 2.2.5 on 2021-06-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210601_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_book_genre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movie_genre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'Engilsh'), ('korean', 'Korean')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
