# Generated by Django 2.2.5 on 2021-06-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210601_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie')], max_length=10, null=True),
        ),
    ]
