# Generated by Django 2.2.5 on 2021-06-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0004_auto_20210601_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_book_genre',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_book_genre',
            field=models.ManyToManyField(related_name='users_book', to='categories.Genre'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_movie_genre',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movie_genre',
            field=models.ManyToManyField(related_name='users_movie', to='categories.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(default='Both', on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
