# Generated by Django 2.2.5 on 2021-06-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210602_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='categories.Category'),
        ),
    ]
