# Generated by Django 2.2.5 on 2021-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210602_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('books', 'Books'), ('movies', 'Movies')], max_length=10),
        ),
    ]
