# Generated by Django 2.2.5 on 2021-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210602_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'Engilsh'), ('korean', 'Korean')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('books', 'Books'), ('movies', 'Movies')], max_length=20),
        ),
    ]
