# Generated by Django 2.2.5 on 2021-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0002_auto_20210602_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favlist',
            name='books',
            field=models.ManyToManyField(related_name='favs', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='movies',
            field=models.ManyToManyField(related_name='favs', to='movies.Movie'),
        ),
    ]
