# Generated by Django 2.2.5 on 2021-06-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='genre',
        ),
    ]
