# Generated by Django 2.2.5 on 2021-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210602_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('both', 'Both')], max_length=10),
        ),
    ]
