# Generated by Django 2.2.5 on 2021-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210602_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('all', 'all')], max_length=10),
        ),
    ]
