# Generated by Django 2.2.5 on 2021-06-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_auto_20210602_2325'),
        ('categories', '0002_remove_category_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('year', models.DateField()),
                ('cover_image', models.ImageField(blank=True, upload_to='movie_photos')),
                ('rating', models.IntegerField()),
                ('cast', models.ManyToManyField(related_name='movie_cast', to='people.Person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='people.Person')),
                ('genre', models.ManyToManyField(related_name='movie', to='categories.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
